// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEn2kWc7lYMH5hZhnL--XEo5ycd1Gzi0',
    appId: '1:212325222171:web:bd979442be90e8f619f5be',
    messagingSenderId: '212325222171',
    projectId: 'mychat-41a19',
    authDomain: 'mychat-41a19.firebaseapp.com',
    storageBucket: 'mychat-41a19.appspot.com',
    measurementId: 'G-GQ4G6MNMZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA97SxVaX1UnfCas2aXSp3KqzIOU8Jjdxw',
    appId: '1:212325222171:android:32ed404513b6e8d319f5be',
    messagingSenderId: '212325222171',
    projectId: 'mychat-41a19',
    storageBucket: 'mychat-41a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vxsAXk05bOmr-nHI8ppNuFH9cAWE01Q',
    appId: '1:212325222171:ios:73096592e9539f4d19f5be',
    messagingSenderId: '212325222171',
    projectId: 'mychat-41a19',
    storageBucket: 'mychat-41a19.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vxsAXk05bOmr-nHI8ppNuFH9cAWE01Q',
    appId: '1:212325222171:ios:a9f6c7102df80d6219f5be',
    messagingSenderId: '212325222171',
    projectId: 'mychat-41a19',
    storageBucket: 'mychat-41a19.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
